export const DASHBOARD_STORAGE_KEY = 'legal-licence-dashboard-v2'
export const LEGACY_RECORD_STORAGE_KEY = 'legal-licence-dashboard-records'
export const THEME_STORAGE_KEY = 'legal-licence-theme'
export const AUTH_STORAGE_KEY = 'legal-licence-auth'
export const LAST_SYNC_STORAGE_KEY = 'legal-licence-last-sync'
